# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "feedbackbird"
client_id = "7c53639ac46d7814cda1cd184f99b057"
application_url = "https://mat-thou-fw-part.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mat-thou-fw-part.trycloudflare.com/auth/callback",
  "https://mat-thou-fw-part.trycloudflare.com/auth/shopify/callback",
  "https://mat-thou-fw-part.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-747f6580.myshopify.com"
